# -*- coding: utf-8 -*-
"""VGG16_1D_HAR_Hala

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ZHR8hcj8VMHiMMtseYjraVw4Ypis--k
"""

from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Conv1D, MaxPooling1D, Flatten, Dense, Dropout

def VGG16_1D(input_shape, num_classes):
    input_layer = Input(shape=input_shape)
    
    # Block 1
    x = Conv1D(64, 3, activation='relu', padding='same')(input_layer)
    x = Conv1D(64, 3, activation='relu', padding='same')(x)
    x = MaxPooling1D(pool_size=2, strides=2)(x)

    # Block 2
    x = Conv1D(128, 3, activation='relu', padding='same')(x)
    x = Conv1D(128, 3, activation='relu', padding='same')(x)
    x = MaxPooling1D(pool_size=2, strides=2)(x)

    # Block 3
    x = Conv1D(256, 3, activation='relu', padding='same')(x)
    x = Conv1D(256, 3, activation='relu', padding='same')(x)
    x = Conv1D(256, 3, activation='relu', padding='same')(x)
    x = MaxPooling1D(pool_size=2, strides=2)(x)

    # Block 4
    x = Conv1D(512, 3, activation='relu', padding='same')(x)
    x = Conv1D(512, 3, activation='relu', padding='same')(x)
    x = Conv1D(512, 3, activation='relu', padding='same')(x)
    x = MaxPooling1D(pool_size=2, strides=2)(x)

    # Block 5
    x = Conv1D(512, 3, activation='relu', padding='same')(x)
    x = Conv1D(512, 3, activation='relu', padding='same')(x)
    x = Conv1D(512, 3, activation='relu', padding='same')(x)
    x = MaxPooling1D(pool_size=2, strides=2)(x)

    # Classification block
    x = Flatten()(x)
    x = Dense(4096, activation='relu')(x)
    x = Dropout(0.5)(x)
    x = Dense(4096, activation='relu')(x)
    x = Dropout(0.5)(x)
    output_layer = Dense(num_classes, activation='softmax')(x)

    # Create model
    model = Model(inputs=input_layer, outputs=output_layer)
    return model